[versions]
fabric-api = "0.159.0+26.2"
fabric-language-kotlin = "1.13.13+kotlin.2.4.10"
fabric-loader = "0.19.5"
fabric-loom = "1.17-SNAPSHOT"
junit = "6.0.3"
kotlin = "2.4.10"
ktlint = "14.2.0"
minecraft = "26.2"
paper = "26.2.build.121-stable"
shadow = "9.3.1"
serialization = "1.11.0"

[libraries]
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
